### ISSUE TITLE
Log questions , answers, and similarity score

### ISSUE THREAD

**Issue by erickhun** [taiwangoldcard/taiwan-bot#11]
We should be able to see (logs?) what questions people asks to the bot , also the answers given and the score (similarity) associated to it. 

Just a log file or even writing it in the spreadsheet would be good, so we could adjust the dataset

**Comment by geekyme** [comment]
write to spreadsheet will be better. Much easier for us to access and fix the data. https://gsuitetips.com/tips/sheets/google-spreadsheet-limitations/

We should be able to manage it all in one sheet:
1) we can analyze the response every week
2) fix our responses
3) delete the rows
