### ISSUE TITLE
Chatbot Recommendation

### ISSUE THREAD

**Issue by jonathanbgn** [taiwangoldcard/taiwan-bot#2]
Hello everyone, @erickhun told me about the FAQ bot project which I found quite interesting.

I've been building many side-projects using NLP these past years and I think the easiest solution would be using sentence embeddings to find the most relevant answer to the user's question. Google recently released a light-weight, easy to implement model that [you can use directly in Google Sheets](https://blog.tensorflow.org/2020/08/introducing-semantic-reactor-explore-nlp-sheets.html) to map questions to the best answers.

Here is an overview of how that works:

<img width="1239" alt="Screen Shot 2020-09-17 at 4 58 34 PM" src="https://user-images.githubusercontent.com/53422011/93449191-09a33680-f907-11ea-9da8-12c5c43e9fa0.png">

You can experiment yourself by going to the [shared spreadsheet](https://docs.google.com/spreadsheets/d/1BNNoL-iLw11eXo3oUcWD8boEFMD0pH-3gB4eArMB7bc/edit?usp=sharing) (you'll need to install [Semantic Reactor](https://gsuite.google.com/marketplace/app/semantic_reactor/509042860915) first).

To implement that into a website we could run the model directly in Javascript on the client side using TensorFlow.js (no server needed), or build a small backend to be able to interact with it through Line for example. I could help with that part if needed!

**Comment by geekyme** [comment]
This is a good idea! At first I thought we would need to do some NLP magic (like determining intent, etc.) first. 

I've written a backend that is able to connect to multiple channels (Line, Facebook Messenger, Telegram, etc.), but no logic on message processing yet. Shall we use that + add the functionality above?

See this PR: @jonathanbgn @erickhun  https://github.com/taiwangoldcard/taiwan-bot/pull/1

**Comment by erickhun** [comment]
love it!  - I  gave it a try : 
![Screen Recording 2020-09-17 at 06 33 PM](https://user-images.githubusercontent.com/3368263/93459523-66f1b480-f914-11ea-93ad-dc6efdad0b00.gif)

- we can just use a collaborative spreadsheet of  Q&A and query that spreadsheet,  it will just work magically 
- we can make it fancier by just scraping our Q&A (but seems like the more variance of questions is better), maybe a spreadsheet is better
- they seem to use it for that ["talk to book"](https://books.google.com/talktobooks/) project, where you just feed it with books, and find the answer. idea 💡: We could feed it with Taiwan immigration law, and get answer from it (cc @fifieldt )
- could potentially feed it with questions/answers from forumsa/line/reddit and have a super super smart bot 🤖

**Comment by fifieldt** [comment]
Relevant laws/regulations:

https://law.moj.gov.tw/Eng/LawClass/LawAll.aspx?PCode=D0080132
https://law.moj.gov.tw/ENG/LawClass/LawAll.aspx?PCode=A0030295
https://law.moj.gov.tw/ENG/LawClass/LawAll.aspx?PCode=D0080204
https://law.moj.gov.tw/ENG/LawClass/LawAll.aspx?PCode=G0340150

**Comment by geekyme** [comment]
@jonathanbgn, we have updated the backend code to have:

- a web server connected to chatbot channels (line)
- a connection to the google sheet above to grab the data you need
- auto deployment to [heroku](http://heroku.com/)

Try the bot [here](https://github.com/taiwangoldcard/taiwan-bot#add-me-on-line). It does nothing but echo your message. All that is missing is the brains to process the message sent by the user. All yours now! 👍

**Comment by jonathanbgn** [comment]
See #8 for a first version of the model (backend version). The model is quite big (almost 1GB) so we should make sure it can run on Heroku!

**Comment by geekyme** [comment]
Closing this as we have a working MVP now :)
