### ISSUE TITLE
Reload data from spreadsheet when it changes

### ISSUE THREAD

**Issue by erickhun** [taiwangoldcard/taiwan-bot#23]
The problem is that now we need to redeploy the bot to repull data from the spreadsheet. 

Some ideas: 
- reload the data at every request, but this could be heavy for embedding all data at each time? 
- reload every X minutes
- any other idea?

**Comment by geekyme** [comment]
I've implemented - `reload every X minutes` in supervisor config:

```
app                              RUNNING   pid 887597, uptime 0:01:09
periodicrestarter                RUNNING   pid 887594, uptime 0:01:10
```

It will restart and therefore pull the new data from the spreadsheet every hour. This is a suboptimal approach as restarting the app means downtime. But quick hack for now.
