### ISSUE TITLE
Manage multiple questions from a single line in Google Spreadsheet

### ISSUE THREAD

**Issue by erickhun** [taiwangoldcard/taiwan-bot#33]
We have too many copy/paste of the same answer in the Google Spreadsheet. It starts becoming hard to maintain, and keep all answer updated. It will make it easier for us to add many variations of a question

The parser should be able to take multiple variations of the same question, from a single line. We can strip it with a new line like : 

<img width="1168" alt="Image 2020-11-03 at 11 03 55 AM" src="https://user-images.githubusercontent.com/3368263/97946168-88273b00-1dc4-11eb-9401-642f21253f17.png">

**Comment by matrinox** [comment]
👀
